### ISSUE TITLE
Modales y popups

### ISSUE THREAD

**Issue by lambanthony** [lambanthony/cm-web#26]
Programación de los popups de promociones

**Comment by lambanthony** [comment]
La idea es crear una estructura común vacía de dependencias que se cargue al iniciar la página. 
Cada logotipo de tatuador tiene asignado los datos que deben rellenar esa estructura.
El modal definitavemente lo creamos al estilo del menú, sin usar los modales de bootstrap.

**Comment by felipeosorio-as** [comment]
Revisar llamada al modal. 
Mismo botón no puede hacer la función de llamar y cambiar los datos de la estructura. 
Función de llamada asignada a row, buscar solución (quitar padding y añadirlo al png?).
